language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8 UV_THREADPOOL_SIZE=1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - bc
      - g++-4.8
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/prebuild-publish.sh
  on:
    tags: true
    branch: master
